server:
  port: 7000
  servlet:
    context-path: /api
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096

spring:
  application: 
    name: spring-jersey
  main:
    banner-mode: "off"